### ISSUE TITLE
Explore and validate a variety of designs

### ISSUE THREAD

**Issue by wdoug** [codefordenver/fresh-food-connect#10]
As a developer, I would like to know that what I am implementing is worthwhile and actually adding value.

Several studies have suggested that the best way to have good ideas is to have a lot of ideas.

NOTE:  This card should probably be broken down into several smaller tasks.

**Comment by wdoug** [comment]
Paper prototypes would probably be super helpful here.

**Comment by switzersc** [comment]
Should tonight's meeting be largely about iterating through a bunch of design/ux prototypes?

**Comment by jenshurley** [comment]
what pages have we not thought about?
