### ISSUE TITLE
Use Server Other Than Webrick

### ISSUE THREAD

**Issue by dkoloditch** [codefordenver/fresh-food-connect#107]

**Comment by wdoug** [comment]
What does this mean, and why @dkoloditch?

**Comment by mpfilbin** [comment]
Webrick is a fairly simple web server packaged with Rails typically for development. It can be used as a production web server with very small load. Typically it is recommended that one uses a more robust HTTP server like Thin, Puma, Passenger, etc.

**Comment by wdoug** [comment]
Closed by https://github.com/codefordenver/fresh-food-connect-api/pull/4
