### ISSUE TITLE
Update <Home/> component

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/fresh-food-connect#112]
- [x] resolve styles
- [x]  resolve images
- [ ]  fix styles 
- [x] update <home/> component html

connects to #111

**Comment by marcusreese** [comment]
My Macbook screen is 13 inches. This morning I looked at https://marcusreese.github.io/connect/ on my wife's larger screen (using Microsoft Edge) and I noticed the tax deductible line falling off the bottom of its container a little. It's something you may want to tweak as you work with it, especially if your screen is larger than mine.

**Comment by dviramontes** [comment]
working from this branch: https://github.com/codefordenver/fresh-food-connect/tree/home-component-update
