### ISSUE TITLE
CSRF Token Requirement on PUT /auth/password

### ISSUE THREAD

**Issue by jensneeoosh** [codefordenver/fresh-food-connect#127]
As a user, I should not need a CSRF token in order to successfully update my password

`Started PUT "/api/v1/auth/password" for 127.0.0.1 at 2015-09-21 20:22:10 -0600
Processing by DeviseTokenAuth::PasswordsController#update as */*
  Parameters: {"reset_password_token"=>"[FILTERED]", "redirect_url"=>"/profile"}
Completed 401 Unauthorized in 1ms (Views: 0.3ms | ActiveRecord: 0.0ms)`

**Comment by wdoug** [comment]
@switzersc, @jensneeoosh, is this still relevant / is it actually in progress?

**Comment by jensneeoosh** [comment]
I don't know if it's still relevant. Shelby, do you mind answering this? 

Jenni Ch'ng
Web Application Engineer
www.jenniferchng.com

**Comment by wdoug** [comment]
@jensneeoosh your
