### ISSUE TITLE
Inform user of password validation beforehand

### ISSUE THREAD

**Issue by wdoug** [codefordenver/fresh-food-connect#166]
As a user I would like to be informed that the password should be 8 or more characters so that I don't get frustrated when I get it wrong and I’m told it needs to be longer.

**Comment by evantbyrne** [comment]
Appears to have already been fixed. :)

![screen shot 2015-10-06 at 10 10 42 pm](https://cloud.githubusercontent.com/assets/138734/10328879/22c6a4d4-6c77-11e5-9453-f105b3b90808.png)

**Comment by evantbyrne** [comment]
Wording feels a tad off though.

**Comment by wdoug** [comment]
The issue was supposed to be that it should inform the user before they try
to sign up instead of after the fact

**Comment by evantbyrne** [comment]
Ah gotcha. Will change that.
