### ISSUE TITLE
UI for login

### ISSUE THREAD

**Issue by DylanKojiCheslin** [codefordenver/fresh-food-connect#18]
As a gardener I want to be able to create an account and log in, so that I can participate in the program.

**Comment by D3s1gnerUX** [comment]
Dylan, complete noob question, but by "UI for login" (and the other "UI" tasks you posted earlier) were you calling for wireframes like we built tonight? I'm trying to nail down the group's terminology and define staged deliverables, also I'd enjoy seeing what you came up with.
