### ISSUE TITLE
Create initial api

### ISSUE THREAD

**Issue by wdoug** [codefordenver/fresh-food-connect#23]
As a FFC user, I would like to have data transmitted via the interwebs so I don't have to rely on carrier pigeons to coordinate the program.

Need CRUD (or to start, just ability to create) for:
- [ ] Users
- [ ] Addresses (could be just part of users)
- [ ] Pickup times 

Maybe:

> Users have one address and haveMany pickup times?

**Comment by wdoug** [comment]
This could be an existing solution

**Comment by wdoug** [comment]
Potentially blocked while investigating SPIKEs

**Comment by dkoloditch** [comment]
Initial API backend created using rails-api. Basic data structure assigned to story 52.
