### ISSUE TITLE
Choose project license

### ISSUE THREAD

**Issue by wdoug** [codefordenver/fresh-food-connect#3]
As someone who finds this project on GitHub, I want to know what the license is so I can decide weather to contribute / copy the project, etc.

Licenses define the legal framework for the project.

**Comment by wdoug** [comment]
Some discussion here already: https://waffle.io/codefordenver/org/cards/55ac29280dc19e1500cdd2b8

**Comment by evantbyrne** [comment]
Are there any objections to using the MIT license?

**Comment by wdoug** [comment]
I doubt there would be any in the Code for Denver group, but I know Wendy had some concerns as to what license is chosen for the overall project.

**Comment by evantbyrne** [comment]
Do you know what her needs are in regards to the license?

**Comment by LittleLadySunshine** [comment]
If you want to keep the code private, it might not be what you want. Otherwise, it's good for open source stuff.

Sincerely,

Denise McCoy
720.456.5825
Denise.L.McCoy@gmail.com

Please forgive the brevity of this message, as it was sent from my iPhone.

**Comment by LittleLadySunshine** [comment]
tldrlegal.com super awesome resource!

**Comment by dviramontes** [comment]
Decided on MIT for now. Closing.
