### ISSUE TITLE
Display list of locations on front-end

### ISSUE THREAD

**Issue by wdoug** [codefordenver/fresh-food-connect#48]
As an organizer I need to be able to see where the gardeners need food to be picked up, so that I can coordinate the cyclists.

**Comment by jenshurley** [comment]
Posted some ideas for layout of locations for program administrator to view: https://drive.google.com/drive/folders/0B4ZZfxczQ-1hfl9KQ0VSWXl0XzJPQXFKdUtSbnFFX3VObXFHOXhYR3k0WEYzOU1Pc0RmdjQ
Their filenames start with "Admin..."

**Comment by lingtran** [comment]
Update from 9/8 project night: it’s easy to put stuff on a map, but we don’t have api routes for it
