### ISSUE TITLE
Design - Wireframe and Style Guides

### ISSUE THREAD

**Issue by jenshurley** [codefordenver/fresh-food-connect#49]
As a developer, I need design documentation that I can implement.

**Comment by jenshurley** [comment]
[]annotated wireframe for gardener main page with components from material-ui.com - add ideas from https://colorado.doortodoororganics.com/signup (as Turner pointed out)
[]styleguide - high fidelity wireframe of main page with some notes on language
[]logo finalization... Ling will check with Wendy
[]diagram full range of functionality: gardener, cyclist, admin, notifications - what happens when... update this
[]low fidelity wireframes for cyclist (map. list of pickup locations) and admin interfaces - Dave
[]stock image for main page - Dave posted some in Drive
[]wireframe of admin pages

**Comment by jenshurley** [comment]
Icons: Use Material Design Icons https://www.google.com/design/icons/ or something else?

Color palette: http://material-ui.com/#/customization/colors

**Comment by lingtran** [comment]
Wendy's feedback will be solicited during check-in on week of August 31.

**Comment by lingtran** [comment]
Update from 9/8 project night: 
- will discuss with SM later;
- Suggestion: mockup nice-to-have stuff
