### ISSUE TITLE
Add basic data structure(s) to backend / API

### ISSUE THREAD

**Issue by dkoloditch** [codefordenver/fresh-food-connect#52]
needed so far: users, locations, donation preferences, donations.

(DONE USING DEVISE - STORY 47) user: first, last, email, pw, role, phone

location: address, city, state, zip, comments, extra (dog, fence, etc), pick-up day, route id (?)

donation preferences: size, comments

donations: created_at, weight, picked_up_at

**Comment by paulgrever** [comment]
Submitted a pull request for locations. Can you review and see if you think it's right? If so I will get to work on donations
