### ISSUE TITLE
Simplify FFC-Client repo

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/fresh-food-connect#59]
As discussed last night, lets use a simpler boilerplate. Original boilerplate was too complex that would require additional costs for maintenance and development.
- [x] root level .\* files
- [x] package.json
- [x] assets directory
- [x] README.md
- [x] fix es-linting issues
- [x] fix build
- [x] npm install, make sure everything runs
- [x] fix webpack->loaders: scss, url-loader
- [x] add our components back (missing is sigup, i think thats all) (PR from Evan)
- [x] prune components/*
- [x] prune constants.js
- [x] fix/wire-up router
- [x] fix scss includes or just use Radium
- [x] fix `lib/ApiClient.js` fixed by Willy
- [x] fix successful login redirect to /profile

**Comment by dviramontes** [comment]
begins migrating to new boilerplate over at:
https://github.com/codefordenver/fresh-food-connect/tree/simpler-boiler-plate

**Comment by wdoug** [comment]
:boom:
