### ISSUE TITLE
Design Logo

### ISSUE THREAD

**Issue by wdoug** [codefordenver/fresh-food-connect#6]
As someone promoting Farm Fresh Connect, I want the project to have a logo, so I can have a cohesive way to draw people's attention.
- [x] Ideate
- [x] Create initial mockups

**Comment by D3s1gnerUX** [comment]
Here are six logo concepts for Fresh Food Connect, for discussion at our next meeting.

![ffc1-logo](https://cloud.githubusercontent.com/assets/13530639/9280460/acd9b3b2-427b-11e5-8e03-94d693ea54fa.png)
![ffc2-logo](https://cloud.githubusercontent.com/assets/13530639/9280461/aceac47c-427b-11e5-95c8-a2bb54005f09.png)
![ffc3-logo](https://cloud.githubusercontent.com/assets/13530639/9280462/acec17b4-427b-11e5-83e2-1cc597bbd990.png)
![ffc4-logo](https://cloud.githubusercontent.com/assets/13530639/9280465/acf02f48-427b-11e5-84b1-1d9876287234.png)
![ffc5-logo](https://cloud.githubusercontent.com/assets/13530639/9280463/aceda822-427b-11e5-8d8b-d9387cd702aa.png)
![ffc6-logo](https://cloud.githubusercontent.com/assets/13530639/9280464/acedcd02-427b-11e5-87db-c70ac17bf207.png)

**Comment by wdoug** [comment]
Sweet
