### ISSUE TITLE
select location for celebration

### ISSUE THREAD

**Issue by karenderrickdavis** [codefordenver/fresh-food-connect#63]

**Comment by karenderrickdavis** [comment]
checking on The Garden and Denver Urban Gardens/Posner Center

**Comment by karenderrickdavis** [comment]
The Garden is available for 9/24.  They can provide food and have a large monitor and wifi.

**Comment by lingtran** [comment]
update from 9/8 project night: Wendy and Turner says either day works. Posner Center classroom is possible location.
