### ISSUE TITLE
Sign Up - 1 Locate

### ISSUE THREAD

**Issue by evantbyrne** [codefordenver/fresh-food-connect#67]
![ffc_signup_a](https://cloud.githubusercontent.com/assets/138734/9648987/cfba3a16-51ab-11e5-9208-76a156de617c.jpeg)

**Comment by wdoug** [comment]
Love having the image directly in the card :+1:

**Comment by lingtran** [comment]
Update from 9/8 project night: 
- this was related to the mockup with zipcode 
- partially merged 
- since it’s not a requirement of MVP, should it be finished? question for POs

**Comment by wdoug** [comment]
This is lower priority given the timeframe, so we are going to move this back to the backlog.
