### ISSUE TITLE
Wireframe or prototype for FFC homepage

### ISSUE THREAD

**Issue by lingtran** [codefordenver/fresh-food-connect#80]

**Comment by wdoug** [comment]
Dave's sweet mockup:
![ffc-material-design1](https://cloud.githubusercontent.com/assets/5432102/9841534/2afb1d68-5a5e-11e5-8a50-b8a8795c2338.jpg)

**Comment by marcusreese** [comment]
I'm working on the HTML+CSS for this landing page. (Thanks for your work on it, Dave!)

**Comment by dviramontes** [comment]
@D3s1gnerUX ^^
