### ISSUE TITLE
Wireframe or prototype of reminder notification e-mail or SMS

### ISSUE THREAD

**Issue by lingtran** [codefordenver/fresh-food-connect#82]

**Comment by jenshurley** [comment]
![email_reminder](https://cloud.githubusercontent.com/assets/7987959/9796897/b7e3555c-57b5-11e5-98db-9a15d780c2a1.png)

**Comment by karenderrickdavis** [comment]
I love this.

On Thu, Sep 10, 2015 at 12:16 PM, Jen Shurley notifications@github.com
wrote:

> [image: email_reminder]
> https://cloud.githubusercontent.com/assets/7987959/9796897/b7e3555c-57b5-11e5-98db-9a15d780c2a1.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codefordenver/fresh-food-connect/issues/82#issuecomment-139332199
> .

## 

_Karen Derrick-Davis, MSSW_

communityhacking.com http://www.communityhacking.com
cityparktimebank.org
denvermetrotimebank.net http://www.denvermetrotimebank.net

mobile: 303-929-0606

**Comment by jenshurley** [comment]
![ffc_reminder_flow](https://cloud.githubusercontent.com/assets/7987959/9823830/f9d9b7fa-5885-11e5-9d3c-5d3c41b5a949.png)

![ffc_donation_instructions](https://cloud.githubusercontent.com/assets/7987959/9823874/441697d4-5886-11e5-8fcd-f6984ec6ab2b.png)

**Comment by jenshurley** [comment]
If we want to know donation size (#13), a screen such as what's below could be added to the reminder-instructions flow after someone clicks link ("I have a donation"). 
![ffc_donation_size](https://cloud.githubusercontent.com/assets/7987959/9824609/297cf9b8-588b-11e5-9988-727e639c09d6.png) The layout doesn't quite look right yet, but just so the idea is out there...

**Comment by jensneeoosh** [comment]
We need the following merge variables needs to be passed from mandrill to mailchimp. 
_|USER_YES_DONATION_URL|_
_|USER_NO_DONATION_URL|_

**Comment by marcusreese** [comment]
In order to communicate the three size options, putting some apples and/or corn cobs out in front of the container would help, because those items are recognizable and their sizes don't vary much. Like in the logo idea from Dave:

<img width="316" alt="grocery bag" src="https://cloud.githubusercontent.com/assets/3712209/9961811/ccb49c0e-5ddf-11e5-83dd-38809abbce89.png">

**Comment by jenshurley** [comment]
You're right, Marcus. We discussed this with Wendy at the last meeting and we decided to go with bags similar to what Dave came up with in the bike trailer illustration. I will draw something up today. You guys are awesome.
