### ISSUE TITLE
Diagram admin to cyclist for pick-up notification

### ISSUE THREAD

**Issue by lingtran** [codefordenver/fresh-food-connect#83]
This is related to card #83.

**Comment by jenshurley** [comment]
![flow_diagram](https://cloud.githubusercontent.com/assets/7987959/9865029/bdf04792-5b0d-11e5-81bc-8f46fd7e2378.png)

**Comment by dviramontes** [comment]
this looks so cool!

**Comment by wdoug** [comment]
:+1: Sweet!
