### ISSUE TITLE
Create simple prototype

### ISSUE THREAD

**Issue by wdoug** [codefordenver/fresh-food-connect#9]
As a product owner focused on delivering the most value in the short time frame of this project, I want to develop a prototype that people can use as quickly as possible, so that we can maximize our learning and feedback around the prototype.

working on it on Aug 3:  Tatiana, Dave, Jen and Brian

**Comment by wdoug** [comment]
My suggestion for the minimum features here would be:

Gardener:
- [x] ability to share that I have food with address
- [ ] ~~ability to set time~~ we will be assigning times so we can optimize the routes

Cyclist (youth employee):
- [ ] ability to know that food is available
- [ ] ability to confirm pick-up -- don't invest in the UI of this as it is not the ultimate UI. The main question is around general assignment of food to a cyclist 
- [x] show locations on map

**Comment by switzersc** [comment]
how come each one of these isnt a user story labelled "MVP"?

**Comment by jkgz** [comment]
+1 Shelby. I had the same thought.

**Comment by wdoug** [comment]
It sounds like just putting the locations on a map is more valuable than the claiming option for the project format.

**Comment by switzersc** [comment]
note: 
must persist the data; 
FRB already as stats for volunteers, pickups etc

**Comment by wdoug** [comment]
We are no longer doing the cyclist piece in favor of just the admin coordination.
