### ISSUE TITLE
Integrate Mandrill + Mailchimp

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/fresh-food-connect#97]
As a user i would like to receive email confirmations for pickup.

AC:
- [x] setup mandrill service
- [x] setup mailchimp service
- [x] link mandrill -> mailchip
- [x] add mailer in `app/mailers` 
- [ ] figure out how to send test email
- [ ] add vars below

connects to #85

**Comment by jensneeoosh** [comment]
When you get to the step where you set up merge_vars:

```
class UserMailer < BaseMandrillMailer
  def welcome(user_id)
    user = User.find(user_id)
    subject = "Welcome to our awesome app!"
    merge_vars = {
      "FIRST_NAME" => user.first_name,
      "USER_URL" => user_url(user),
    }
    body = mandrill_template("welcome", merge_vars)

    send_mail(user.email, subject, body)
  end
end
```

We'll need the following for the various email templates:
Email Registration: CONFIRM_EMAIL_URL
Reset Password: RESET_PASSWORD_URL

**Comment by dviramontes** [comment]
initial setup: https://github.com/codefordenver/fresh-food-connect-api/pull/2

**Comment by wdoug** [comment]
Connects to #13
